### ISSUE TITLE
Error at startup with docker-compose ("socket hang up")

### ISSUE THREAD

**Issue by fabriziocucci** [hammoaj/node-red-contrib-cloudantplus#1]
I'd like to report an interesting issue while working in a Docker context. Although, it may be worth mentioning that I'm a Node-RED newbie so there may be an easy solution for my problem.

My Node-RED `Dockerfile` looks like this:

```docker
FROM nodered/node-red-docker
RUN npm install node-red-contrib-pdf-hummus
RUN npm install node-red-contrib-cloudantplus
```

My `docker-compose.yml` looks like this:

```yaml
version: '3'

services:
  my-pipeline:
    build: .
    ports:
     - "1880:1880"
    volumes:
     - ./data/flows.json:/data/flows.json
    links:
     - cloudant-developer
  cloudant-developer:
    image: ibmcom/cloudant-developer:latest
    hostname: cloudant.dev
    ports:
      - "8080:80"
    volumes:
      - cloudant-developer:/srv

volumes:
  cloudant-developer:
```

When I run `docker-compose up`, I can see from the Node-RED logs the following issue:

> my-pipeline_1  | 19 Nov 23:10:43 - [error] [cloudantplus out:insert] socket hang up

Now, there are few things I can't explain:
1. my flow contains an `inject` node but the option for firing at startup is not ticked in the node configuration. So, why is the `cloudantplus out` node triggered at startup?
2. after that, if I manually trigger the flow using the `inject` node I get the same issue reported during startup (i.e. "socket hang up") but if I make a non significant change (e.g. moving some node) in order to enable the `Deploy` button and then I actually re-deploy, everything works perfectly. Why a re-deploy of the exact same flow is required in order to fix the issue?

As a further note, I've tried to run the same images without docker-compose by starting first Cloudant Developer and then Node-RED, giving some time to Cloudant to startup and everything worked as expected.

Ultimately, it seems that the issue is caused by the `cloudant out` node trying to connect to Cloudant before the latter is actually up and running. But the worst thing is that, after the first attempt, the `cloudant out` node remains in a broken state until another deploy is triggered.

Is there something that can be "fixed" in the `cloudant out` node or the common approach is to ping some health endpoint of cloudant [as suggested in the Docker documentation](https://docs.docker.com/compose/startup-order/)?
